# Generated by Django 4.1.3 on 2023-01-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(max_length=200)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('production_coefficient', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('fuel_factor', models.FloatField()),
                ('carbon_coefficient', models.FloatField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coTwo.material')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=200)),
                ('capacity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_trips', models.PositiveIntegerField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('total_carbon_emission', models.FloatField(blank=True, default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coTwo.materialtransportation')),
            ],
        ),
        migrations.AddField(
            model_name='materialtransportation',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coTwo.transport'),
        ),
        migrations.CreateModel(
            name='MaterialProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_material_quantity', models.FloatField(default=0)),
                ('material_quantity_unit', models.CharField(choices=[('KG', 'Kilogrammes'), ('M3', 'Cubic metres')], default='KG', max_length=2)),
                ('total_carbon_emission', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coTwo.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveIntegerField(default=0)),
                ('electrical_consumption', models.FloatField(default=0)),
                ('electrical_coefficient', models.FloatField(default=0)),
                ('total_carbon_coefficient', models.FloatField(default=0)),
                ('type_of_energy', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coTwo.energytype')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quantity', models.FloatField()),
                ('lifespan', models.PositiveIntegerField()),
                ('rate_of_repair', models.FloatField()),
                ('repair_interval', models.PositiveIntegerField()),
                ('total_emission_coefficient', models.FloatField(default=0)),
                ('maintenance_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coTwo.material')),
            ],
        ),
    ]
