# Generated by Django 4.1.3 on 2023-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
