# Generated by Django 4.1.3 on 2023-01-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproduction',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='coTwo.project'),
        ),
    ]
