# Generated by Django 4.1.3 on 2023-01-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0003_materialproduction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmaintenance',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='coTwo.project'),
        ),
        migrations.AddField(
            model_name='materialoperation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='coTwo.project'),
        ),
        migrations.AddField(
            model_name='projecttransportation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='coTwo.project'),
        ),
    ]
