# Generated by Django 4.1.3 on 2023-01-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0004_materialmaintenance_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
