# Generated by Django 4.1.3 on 2023-01-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0005_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='  '),
        ),
    ]
