# Generated by Django 4.1.3 on 2023-01-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0006_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransportation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='coTwo.project'),
        ),
        migrations.AlterField(
            model_name='projecttransportation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_transport', to='coTwo.project'),
        ),
    ]
