# Generated by Django 4.1.3 on 2023-01-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coTwo', '0007_materialtransportation_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='net_carbon_emissions',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='materialproduction',
            name='total_carbon_emission',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
